// players save to local.storage, game can check local storage and recieve them
class Game {
  constructor() {
    this.player1 = new Player("1");
    this.player2 = new Player("2");
    this.deck = [
      {type: "ace",
      suit: "blue",
      src: "./assets/blue-01.png"},
      {type: "two",
      suit: "blue",
      src: "./assets/blue-02.png"},
      {type: "three",
      suit: "blue",
      src: "./assets/blue-03.png"},
      {type: "four",
      suit: "blue",
      src: "./assets/blue-04.png"},
      {type: "five",
      suit: "blue",
      src: "./assets/blue-05.png"},
      {type: "six",
      suit: "blue",
      src: "./assets/blue-06.png"},
      {type: "seven",
      suit: "blue",
      src: "./assets/blue-07.png"},
      {type: "eight",
      suit: "blue",
      src: "./assets/blue-08.png"},
      {type: "nine",
      suit: "blue",
      src: "./assets/blue-09.png"},
      {type: "ten",
      suit: "blue",
      src: "./assets/blue-10.png"},
      {type: "jack",
      suit: "blue",
      src: `./assets/blue-jack`},
      {type: "queen",
      suit: "blue",
      src: "./assets/blue-queen.png"},
      {type: "king",
      suit: "blue",
      src: "./assets/blue-king.png"},
      {type: "ace",
      suit: "gold",
      src: "./assets/gold-01.png"},
      {type: "two",
      suit: "gold",
      src: "./assets/gold-02.png"},
      {type: "three",
      suit: "gold",
      src: "./assets/gold-03.png"},
      {type: "four",
      suit: "gold",
      src: "./assets/gold-04.png"},
      {type: "five",
      suit: "gold",
      src: "./assets/gold-05.png"},
      {type: "six",
      suit: "gold",
      src: "./assets/gold-06.png"},
      {type: "seven",
      suit: "gold",
      src: "./assets/gold-07.png"},
      {type: "eight",
      suit: "gold",
      src: "./assets/gold-08.png"},
      {type: "nine",
      suit: "gold",
      src: "./assets/gold-09.png"},
      {type: "ten",
      suit: "gold",
      src: "./assets/gold-10.png"},
      {type: "jack",
      suit: "gold",
      src: `./assets/gold-jack`},
      {type: "queen",
      suit: "gold",
      src: "./assets/gold-queen.png"},
      {type: "king",
      suit: "gold",
      src: "./assets/gold-king.png"},
      {type: "ace",
      suit: "green",
      src: "./assets/green-01.png"},
      {type: "two",
      suit: "green",
      src: "./assets/green-02.png"},
      {type: "three",
      suit: "green",
      src: "./assets/green-03.png"},
      {type: "four",
      suit: "green",
      src: "./assets/green-04.png"},
      {type: "five",
      suit: "green",
      src: "./assets/green-05.png"},
      {type: "six",
      suit: "green",
      src: "./assets/green-06.png"},
      {type: "seven",
      suit: "green",
      src: "./assets/green-07.png"},
      {type: "eight",
      suit: "green",
      src: "./assets/green-08.png"},
      {type: "nine",
      suit: "green",
      src: "./assets/green-09.png"},
      {type: "ten",
      suit: "green",
      src: "./assets/green-10.png"},
      {type: "jack",
      suit: "green",
      src: `./assets/green-jack`},
      {type: "queen",
      suit: "green",
      src: "./assets/green-queen.png"},
      {type: "king",
      suit: "green",
      src: "./assets/green-king.png"},
      {type: "ace",
      suit: "red",
      src: "./assets/red-01.png"},
      {type: "two",
      suit: "red",
      src: "./assets/red-02.png"},
      {type: "three",
      suit: "red",
      src: "./assets/red-03.png"},
      {type: "four",
      suit: "red",
      src: "./assets/red-04.png"},
      {type: "five",
      suit: "red",
      src: "./assets/red-05.png"},
      {type: "six",
      suit: "red",
      src: "./assets/red-06.png"},
      {type: "seven",
      suit: "red",
      src: "./assets/red-07.png"},
      {type: "eight",
      suit: "red",
      src: "./assets/red-08.png"},
      {type: "nine",
      suit: "red",
      src: "./assets/red-09.png"},
      {type: "ten",
      suit: "red",
      src: "./assets/red-10.png"},
      {type: "jack",
      suit: "red",
      src: `./assets/red-jack`},
      {type: "queen",
      suit: "red",
      src: "./assets/red-queen.png"},
      {type: "king",
      suit: "red",
      src: "./assets/red-king.png"},
    ];
    this.wild = {type: "wild",
    suit: "wild",
    src: "./assets/wild.png"};
  }
  shuffle() {
    for (var i = 0; i < this.deck.length; i++) {
    var randomDigit = Math.floor(Math.random() *52);
    this.deck.unshift(this.deck.splice(randomDigit, 1)) //seems to sometimes unshift an array with the object in it, instead of just the object. 
  }
  }
}


// module.exports = Game;
